service: bill-splitter-webservice
frameworkVersion: '>=4'
provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  region: us-east-1
  stage: ${opt:stage}
functions:
  api:
    handler: bootstrap
    events:
      - http:
          path: /ping
          method: GET
      - http:
          path: /tabscanner/process
          method: POST
      - http:
          path: /tabscanner/result/{token}
          method: GET
package:
  patterns:
    - '!*/**'
    - bootstrap